#!/usr/bin/env zsh

# Welcome to Matt's laptop script! Forked from thoughbot.
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

# Touch a .zshrc file so we can source it later and not have the system fail
touch ~/.zshrc

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -d "$HOME/Sites/" ]; then
  mkdir "$HOME/Sites"
fi

fancy_echo() {
  printf "\n%b\n" "$1"
}

if [[ -f /etc/zshenv ]]; then
  fancy_echo "Fixing OSX zsh environment bug ..."
    sudo mv /etc/{zshenv,zshrc}
fi

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

fancy_echo "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
  brew update

fancy_echo "Tap Homebrew dependencies ..."
  brew tap homebrew/dupes

fancy_echo "Installing git, Node.js, Z Script ..."
  brew install git node z

fancy_echo "Installing rbenv, to change Ruby versions ..."
  brew install rbenv
  eval "$(rbenv init -)"
  source ~/.zshrc

fancy_echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
  brew install rbenv-gem-rehash

fancy_echo "Installing ruby-build, to install Rubies ..."
  brew install ruby-build

fancy_echo "Installing Ruby 2.0.0-p247 ..."
  rbenv install 2.0.0-p247

fancy_echo "Setting Ruby 2.0.0-p247 as global default Ruby ..."
  rbenv global 2.0.0-p247
  rbenv rehash
  source ~/.zshrc

fancy_echo "Updating to latest Rubygems version ..."
  gem update --system

fancy_echo "Installing critical Ruby gems for development ..."
  gem install bundler compass bourbon neat --no-document

fancy_echo "Installing Essential NPM Packages - Grunt, Yeoman and Bower, because you need them ..."
  npm install -g yo grunt-cli bower npm-check-updates

# Get rid of zshrc and move on to the dotfiles
rm ~/.zshrc

fancy_echo "Cloning and installing dotfiles ..."
  git clone https://github.com/mattbanks/dotfiles.git ~/.dotfiles
  cd ~/.dotfiles
  fonts/copy
  script/bootstrap
