#!/usr/bin/env zsh

# Welcome to Matt's laptop script! Forked from thoughbot.
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

fancy_echo() {
  printf "\n%b\n" "$1"
}

if [ ! -d "$HOME/.bin/" ]; then
  fancy_echo "Creating home .bin folder ..."
  mkdir "$HOME/.bin"
fi

if [ ! -d "$HOME/Sites/" ]; then
  fancy_echo "Creating Sites folder ..."
  mkdir "$HOME/Sites"
fi

if [[ -f /etc/zshenv ]]; then
  fancy_echo "Fixing OSX zsh environment bug ..."
    sudo mv /etc/{zshenv,zshrc}
fi

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

fancy_echo "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
  brew update

fancy_echo "Tap Homebrew dependencies ..."
  brew tap homebrew/dupes

fancy_echo "Cloning and installing dotfiles, running setup scripts ..."
  git clone https://github.com/mattbanks/dotfiles.git ~/.dotfiles
  cd ~/.dotfiles
  script/bootstrap
  fonts/copy
  iterm2/setup
  sublime3/setup
  xcode/setup

fancy_echo "Setting up hosts file ..."
  cat /etc/hosts | grep sites.whatup || sudo printf "\n##\n# Matt's hosts\n##\n192.168.56.101 sites.whatup\n" | sudo tee -a /etc/hosts

fancy_echo "Cloning Vagrant dev box ..."
  git clone https://github.com/mattbanks/vagrant-dev-box.git ~/vmdevbox

fancy_echo "Installing git, Node.js, Z Script ..."
  brew install git node z

fancy_echo "Installing rbenv, to change Ruby versions ..."
  brew install rbenv

fancy_echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
  brew install rbenv-gem-rehash

fancy_echo "Installing ruby-build, to install Rubies ..."
  brew install ruby-build

fancy_echo "Installing Ruby 2.0.0-p247 ..."
  rbenv install 2.0.0-p247

fancy_echo "Setting Ruby 2.0.0-p247 as global default Ruby ..."
  rbenv global 2.0.0-p247
  rbenv rehash
  source ~/.zshrc

fancy_echo "Updating to latest Rubygems version ..."
  gem update --system

fancy_echo "Installing critical Ruby gems for Rails development ..."
  gem install bundler rails compass --no-document

fancy_echo "Installing Essential NPM Packages - Grunt, Yeoman and Bower, because you need them ..."
  npm install -g yo grunt-cli bower npm-check-updates

fancy_echo "Setting up OSX defaults ..."
  cd ~/.dotfiles
  osx/set-defaults.sh
